### ISSUE TITLE
Hyphen separator is hardcoded?

### ISSUE THREAD

**Issue by TheBB** [Malabarba/Nameless#9]
Many packages use other styles of separators between the package name and the "actual" name. For example, in Spacemacs, we use
- `-` for public-facing variables
- `--` for private variables
- `/` for public-facing (mostly interactive) functions
- `//` for private functions
- `|` for macros

It would be nice if nameless could be configured with different separators.

**Comment by TheBB** [comment]
Just removing the hyphen in the `nameless--name-regexp` function suffices for my ends, at least. I'm aware that the separator won't be concealed in this case, but it doesn't seem practical to do so anyway. For me, `spacemacs` is the prefix, and not `spacemacs-`.

**Comment by Malabarba** [comment]
I thought about supporting general separators when I was first writing this. Since the recommended elisp style is to use hyphens I decided not to invest the effort supporting other stuff.

I know some packages use different separators, so if you'd like to implement support for this it would be a welcome feature. The correct way would be to replace the hardcoded `-` with a variable `nameless-separator`. whose default value is `"-"`.

**Comment by Malabarba** [comment]
Nevermind. Ended up doing it.
You can set `nameless-separator` to `nil`.

**Comment by TheBB** [comment]
Great! That's much simpler than what I had in mind.
